parameters:
  host_ip: machine_a_ip
  host_name: machine_a

  peers: machine_b_ip

  in: true
  topic_list_paths_incoming: /ws/example/4_external_master/chatter_topic.txt
  source_names: machine_b

  ros1_ip_key: machine_a_ip