parameters:
  host_ip: machine_a_ip
  peers: machine_b_ip
  topic_list_paths_incoming: /ws/example/3_multi_machine_relay/chatter_topic.txt
windows:
  - name: LISTEN
    splits:
      - commands:
        - ros2 topic echo /chatter