parameters:
  session_dir: /ws/example/2_native_topic
  peer_dir: ${session_dir}/b

  ip_local: machine_b_ip
  local_name: b
  ip_remote: machine_a_ip
  remote_name: a

  out: true
  topic_list_paths_outbound: ${session_dir}/b_to_a_topics.txt
