parameters:
  session_dir: /ws/example/3_comp_occ_grid
  peer_dir: ${session_dir}/b

  ip_local: machine_b_ip
  local_name: b
  ip_remote: machine_a_ip
  remote_name: a

  qos_config_file: ${session_dir}/qos.yaml

  in: true
  topic_list_paths_inbound: ${session_dir}/a_to_b_topics.txt

  out: true
  topic_list_paths_outbound: ${session_dir}/b_to_a_topics.txt

  topic_monitor: true

  heartbeat: true
  heartbeat_out_topics: /heartbeat_b
  heartbeat_in_topic: /heartbeat_a

  rs: true
  rs_restamp_topics: /costmap/costmap
  rs_topic_suffix: /restamped

  comp: true
  comp_config_file: ${peer_dir}/compression.yaml
  comp_algorithm: bz2
