parameters:
  session_dir: /ws/example/3_comp_occ_grid
  peer_dir: ${session_dir}/a

  ip_local: machine_a_ip
  local_name: a
  ip_remote: machine_b_ip
  remote_name: b

  qos_config_file: ${session_dir}/qos.yaml

  in: true
  topic_list_paths_inbound: ${session_dir}/b_to_a_topics.txt

  out: true
  topic_list_paths_outbound: ${session_dir}/a_to_b_topics.txt

  topic_monitor: true

  heartbeat: true
  heartbeat_out_topics: /heartbeat_a
  heartbeat_in_topic: /heartbeat_b

  deco: true
  deco_config_file: ${peer_dir}/decompression.yaml
  deco_algorithm: bz2
