parameters:
  session_dir: /ws/example/1_heartbeat
  peer_dir: ${session_dir}/a

  ip_local: machine_a_ip
  local_name: a
  ip_remote: machine_b_ip
  remote_name: b

  in: true
  topic_list_paths_inbound: ${session_dir}/b_to_a_topics.txt

  out: true
  topic_list_paths_outbound: ${session_dir}/a_to_b_topics.txt

  heartbeat: true
  heartbeat_out_topics: /heartbeat_a
  heartbeat_in_topic: /heartbeat_b
