parameters:
  session_dir: /ws/example/4_comp_occ_grid_zen
  peer_dir: ${session_dir}/b

  ip_local: machine_b_ip
  local_name: b
  ip_remote: machine_a_ip
  remote_name: a

  in: true
  topic_list_paths_inbound: ${session_dir}/a_to_b_topics.txt

  out: true
  topic_list_paths_outbound: ${session_dir}/b_to_a_topics.txt

  zen: true
  zen_pub_allow: /ota/b/.*
  zen_sub_allow: /ota/a/.*
  zen_transport: udp
  zen_mode: router
  zen_endpoint_role: connect
  zen_main_ip: machine_a_ip
  zen_main_port: 7447
  zen_qos_pub: |1
         {
           key_exprs: [ "ota/b/costmap/costmap_restamped_compressed" ],
           config: { priority: "data", express: true }
         },
         {
           key_exprs: [ "ota/b/heartbeat_b" ],
           config: { priority: "real_time" }
         }

  topic_monitor: true

  heartbeat: true
  heartbeat_out_topics: /heartbeat_b
  heartbeat_in_topic: /heartbeat_a

  rs: true
  rs_restamp_topics: /costmap/costmap
  rs_topic_suffix: /restamped

  comp: true
  comp_config_file: ${peer_dir}/compression.yaml
  comp_algorithm: bz2
