parameters:
  host_ip: machine_b_ip
  host_name: machine_b

  peers: machine_a_ip

  out: true
  topic_list_paths_outgoing: /ws/example/4_external_master/chatter_topic.txt

  ros1_ip_key: machine_b_ip