parameters:
  host_ip: machine_b_ip
  host_name: machine_b

  peers: machine_a_ip

  out: true
  topic_list_paths_outgoing: /ws/example/3_multi_machine_relay/chatter_topic.txt
windows:
  - name: TALK
    splits:
      - commands:
        - |
          ros2 topic pub /chatter std_msgs/msg/String "data: 'hello from talker'"