parameters:
  host_ip: machine_a_ip
  peers: "machine_b_ip"
windows:
  - name: LISTEN
    splits:
      - commands:
        - ros2 topic echo /chatter
      # - commands:
      #   - ros2 topic info /chatter --verbose
