parameters:
  host_ip: machine_b_ip
  peers: "machine_a_ip"
windows:
  - name: TALK
    splits:
      - commands:
        - |
          ros2 topic pub /chatter std_msgs/msg/String "data: 'hello from talker'"
      # - commands:
      #   - ros2 topic info /chatter --verbose